env:
  AWS_DEFAULT_REGION: "ap-southeast-2"

steps:
  - name: ":cloudformation: Validate template"
    command: "make validate"
    
  - wait

  - name: ":cloudformation: Deploy template"
    command: "make deploy"
